// <auto-generated />
using System;
using Financeiro.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Financeiro.Infrastructure.Persistencia.Migracoes
{
    [DbContext(typeof(FinanceiroDbContext))]
    [Migration("20260914163411_EsquemaInicialFinanceiro")]
    partial class EsquemaInicialFinanceiro
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("financeiro")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Financeiro.Domain.Transacoes.Transacao", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<Guid?>("ContaId")
                        .HasColumnType("uuid")
                        .HasColumnName("conta_id");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<DateTimeOffset?>("ExcluidoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("excluido_em");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("tipo");

                    b.Property<long>("Valor")
                        .HasColumnType("bigint")
                        .HasColumnName("valor");

                    b.HasKey("UsuarioId", "Id");

                    b.HasIndex("UsuarioId", "AtualizadoEm", "Id")
                        .HasDatabaseName("ix_transacoes_usuario_atualizado_id");

                    b.HasIndex("UsuarioId", "Data", "Id")
                        .HasDatabaseName("ix_transacoes_usuario_data_id");

                    b.ToTable("transacoes", "financeiro");
                });
#pragma warning restore 612, 618
        }
    }
}
